<?xml version="1.0" encoding="utf-8"?><Database Name="FinancesDB" Class="LinkToDBDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=CHASE-PC\SQLEXPRESS2014;Initial Catalog=FinancesDB;Persist Security Info=True;User ID=blend" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="FinancesDBConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.BillHistorys" Member="BillHistories">
    <Type Name="BillHistory">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Version" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CreationDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="ModifyDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Amount" Type="System.Decimal" DbType="Decimal(9,2) NOT NULL" CanBeNull="false" />
      <Column Name="BillId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DatePaid" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="Payee" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="PaymentTypeId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IssueDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Association Name="Bill_BillHistory" Member="Bill" ThisKey="BillId" OtherKey="Id" Type="Bill" IsForeignKey="true" />
      <Association Name="PaymentType_BillHistory" Member="PaymentType" ThisKey="PaymentTypeId" OtherKey="Id" Type="PaymentType" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Bills" Member="Bills">
    <Type Name="Bill">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Version" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CreationDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="ModifyDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="DueDate" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="Amount" Type="System.Decimal" DbType="Decimal(9,2) NOT NULL" CanBeNull="false" />
      <Column Name="Payee" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="PaymentTypeId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="StaysSame" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IssueDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="Shared" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="Bill_BillHistory" Member="BillHistories" ThisKey="Id" OtherKey="BillId" Type="BillHistory" />
      <Association Name="PaymentType_Bill" Member="PaymentType" ThisKey="PaymentTypeId" OtherKey="Id" Type="PaymentType" IsForeignKey="true" />
      <Association Name="User_Bill" Member="User" ThisKey="UserId" OtherKey="Id" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.LoanHistorys" Member="LoanHistories">
    <Type Name="LoanHistory">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Version" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CreationDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="ModifyDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="AddPayment" Type="System.Decimal" DbType="Decimal(9,2) NOT NULL" CanBeNull="false" />
      <Column Name="BasicPayment" Type="System.Decimal" DbType="Decimal(9,2) NOT NULL" CanBeNull="false" />
      <Column Name="DatePaid" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="Escrow" Type="System.Decimal" DbType="Decimal(9,2) NOT NULL" CanBeNull="false" />
      <Column Name="Interest" Type="System.Decimal" DbType="Decimal(9,2) NOT NULL" CanBeNull="false" />
      <Column Name="LoanId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PaymentTypeId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Loan_LoanHistory" Member="Loan" ThisKey="LoanId" OtherKey="Id" Type="Loan" IsForeignKey="true" />
      <Association Name="PaymentType_LoanHistory" Member="PaymentType" ThisKey="PaymentTypeId" OtherKey="Id" Type="PaymentType" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Loans" Member="Loans">
    <Type Name="Loan">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Version" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CreationDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="ModifyDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="AddPayment" Type="System.Decimal" DbType="Decimal(9,2) NOT NULL" CanBeNull="false" />
      <Column Name="Escrow" Type="System.Decimal" DbType="Decimal(9,2) NOT NULL" CanBeNull="false" />
      <Column Name="FirstPaymentDate" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="InterestRate" Type="System.Decimal" DbType="Decimal(9,5) NOT NULL" CanBeNull="false" />
      <Column Name="LoanAmount" Type="System.Decimal" DbType="Decimal(9,2) NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Term" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PaymentTypeId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="InterestCompDaily" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="InterestCompMonthly" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="Loan_LoanHistory" Member="LoanHistories" ThisKey="Id" OtherKey="LoanId" Type="LoanHistory" />
      <Association Name="PaymentType_Loan" Member="PaymentType" ThisKey="PaymentTypeId" OtherKey="Id" Type="PaymentType" IsForeignKey="true" />
      <Association Name="User_Loan" Member="User" ThisKey="UserId" OtherKey="Id" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PaymentTypes" Member="PaymentTypes">
    <Type Name="PaymentType">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Version" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CreationDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="ModifyDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="PaymentsPerYear" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="PaymentType_BillHistory" Member="BillHistories" ThisKey="Id" OtherKey="PaymentTypeId" Type="BillHistory" />
      <Association Name="PaymentType_Bill" Member="Bills" ThisKey="Id" OtherKey="PaymentTypeId" Type="Bill" />
      <Association Name="PaymentType_LoanHistory" Member="LoanHistories" ThisKey="Id" OtherKey="PaymentTypeId" Type="LoanHistory" />
      <Association Name="PaymentType_Loan" Member="Loans" ThisKey="Id" OtherKey="PaymentTypeId" Type="Loan" />
    </Type>
  </Table>
  <Table Name="dbo.Users" Member="Users">
    <Type Name="User">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Version" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CreationDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="ModifyDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="FirstName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="LastName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="Char(128) NOT NULL" CanBeNull="false" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="User_Bill" Member="Bills" ThisKey="Id" OtherKey="UserId" Type="Bill" />
      <Association Name="User_Loan" Member="Loans" ThisKey="Id" OtherKey="UserId" Type="Loan" />
    </Type>
  </Table>
</Database>